# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Python Tutorial for Artists
email: scott@propersquid.com
description: > # this means to ignore newlines until "baseurl:"
  A simple Python tutorial for artists working in animation, VFX, or games.
  This tutorial focuses on Python 2.7.
baseurl: "/python-tutorial" # the subpath of your site, e.g. /blog
url: "https://scott-wilson.github.io" # the base hostname & protocol for your site

# GitHub Links
github_download_url: https://github.com/scott-wilson/python-tutorial/archive/master.zip
github_source_url: https://github.com/scott-wilson/python-tutorial
github_issues_url: https://github.com/scott-wilson/python-tutorial/issues

# Build settings
markdown: redcarpet
redcarpet:
  extensions:
    - fenced_code_blocks
    - tables
    - autolink
    - with_toc_data
